### ISSUE TITLE
Plotly_key.txt file missing from repository

### ISSUE THREAD

**Issue by italopguimaraes** [gianlucahmd/loads_clustering#1]
Hello, I'm trying to run the loads_clustering.ipynb code, but it's missing a file called plotly_key.txt, could you put it in the github repository, please?

**Comment by gianlucahmd** [comment]
Hey Italo,

the file contains my plotly API key, which I didn't include for obvious reasons :) 
You need to generate your own API key and put it in a txt file called `plotly_key.txt`. You can do that by creating a free account on plot.ly -> Profile -> Settings -> API Key.

Cheers!
G
